### ISSUE TITLE
Add beautifier to unibeautify and update VSCode plugin

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-csscomb#11]
Noticed that it is not yet added to the beautifiers:

```
Extension Host] Error: Beautifier not found: CSScomb
    at Unibeautify.beautify (/Users/marvinheilemann/.vscode/extensions/glavin001.unibeautify-vscode-0.6.1/node_modules/unibeautify/src/beautifier.ts:309:9)
    at EditProvider.beautifyOptions.then.beautifyOptions (/Users/marvinheilemann/.vscode/extensions/glavin001.unibeautify-vscode-0.6.1/src/EditProvider.ts:80:28)
    at <anonymous>
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
log.ts:171   ERR Beautifier not found: CSScomb: Error: Beautifier not found: CSScomb
    at Unibeautify.beautify (/Users/marvinheilemann/.vscode/extensions/glavin001.unibeautify-vscode-0.6.1/node_modules/unibeautify/src/beautifier.ts:309:9)
    at EditProvider.beautifyOptions.then.beautifyOptions (/Users/marvinheilemann/.vscode/extensions/glavin001.unibeautify-vscode-0.6.1/src/EditProvider.ts:80:28)
    at <anonymous>
```

**Comment by Glavin001** [comment]
This issue belongs in https://github.com/Unibeautify/vscode 

It is fairly trivial: https://github.com/Unibeautify/vscode/commit/c827224e35376feb6bc9181e678e2afe1aebfb7c

Would you like to make the Pull Request? 😃  Let me know if you have any questions!

**Comment by Glavin001** [comment]
This issue was moved to Unibeautify/vscode#136
